# Generated by Django 5.2.8 on 2025-11-10 16:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_reward_at', models.DateTimeField(blank=True, null=True)),
                ('balance_ecg', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_staked', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_rewards', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='pag.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('STAKE', 'Stake'), ('REWARD', 'Reward')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('recipient_address', models.CharField(max_length=42)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pag.userprofile')),
            ],
        ),
    ]
