# Generated by Django 5.2.8 on 2025-12-28 11:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_received_signup_bouns', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bouns_received', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('referrer_bouns', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('staked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_date', models.DateTimeField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-staked_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('wallet_type', models.CharField(default='ethereum', max_length=20)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('token_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_staked', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('wallet_address', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_reward_at', models.DateTimeField(blank=True, null=True)),
                ('rewards_count', models.IntegerField(default=0)),
                ('referral_points', models.IntegerField(default=0)),
                ('balance_ecg', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_staked', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_rewards', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('flat_bonus_self', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('flat_bonus_upline', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='pag.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='pag.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TokenReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_type', models.CharField(choices=[('signup_referral', 'پاداش ثبت نام زیرمجموعه'), ('staking_self', 'پاداش استیکینگ خود کاربر'), ('staking_referral', 'پاداش استیکینگ زیر مجموعه'), ('staking_unlock', 'برداشت از استیکینگ')], max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pag.referral')),
                ('related_staking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pag.staking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_rewards', to='pag.walletuser')),
            ],
        ),
        migrations.AddField(
            model_name='staking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakings', to='pag.walletuser'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='pag.walletuser'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_referrals', to='pag.walletuser'),
        ),
    ]
