# Generated by Django 5.2.8 on 2025-12-28 11:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=200, unique=True)),
                ('transaction_type', models.CharField(choices=[('STAKE', 'Stake'), ('REWARD', 'Reward'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('amount_ecg', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('amount_usdt', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('amount_bnb', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('recipient_address', models.CharField(max_length=200)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pag.userprofile')),
            ],
        ),
    ]
