# Generated by Django 5.2.8 on 2025-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0002_referrallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rewards_count',
            field=models.IntegerField(default=0),
        ),
    ]
