# Generated by Django 5.2.8 on 2025-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0003_userprofile_rewards_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
    ]
