# Generated by Django 5.2.8 on 2025-12-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0003_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='has_received_signup_bouns',
            new_name='has_received_signup_bonus',
        ),
        migrations.RenameField(
            model_name='staking',
            old_name='bouns_received',
            new_name='bonus_received',
        ),
        migrations.RenameField(
            model_name='staking',
            old_name='referrer_bouns',
            new_name='referrer_bonus',
        ),
        migrations.AlterField(
            model_name='staking',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
