# Generated by Django 5.2.8 on 2025-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0004_rename_has_received_signup_bouns_referral_has_received_signup_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenreward',
            name='related_referral',
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='staking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tokenreward',
            name='related_staking',
        ),
        migrations.RemoveField(
            model_name='tokenreward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='referral_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralLink',
        ),
        migrations.DeleteModel(
            name='Staking',
        ),
        migrations.DeleteModel(
            name='TokenReward',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
