# Generated by Django 5.2.8 on 2025-12-31 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0005_remove_tokenreward_related_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_received_signup_bonus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='pag.walletuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_referrals', to='pag.walletuser')),
            ],
        ),
        migrations.CreateModel(
            name='Staking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bonus_received', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('referrer_bonus', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('staked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_date', models.DateTimeField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakings', to='pag.walletuser')),
            ],
            options={
                'ordering': ['-staked_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_type', models.CharField(choices=[('signup_referral', 'پاداش ثبت\u200cنام زیرمجموعه'), ('staking_self', 'پاداش استیکینگ خود کاربر'), ('staking_referral', 'پاداش استیکینگ زیرمجموعه'), ('staking_unlock', 'برداشت از استیکینگ')], max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pag.referral')),
                ('related_staking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pag.staking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_rewards', to='pag.walletuser')),
            ],
        ),
    ]
