# Generated by Django 5.2.8 on 2025-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0005_remove_transaction_amount_transaction_amount_bnb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_bnb',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_ecg',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_usdt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
