# Generated by Django 5.2.8 on 2025-11-10 18:21

import django.db.models.deletion
import pag.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0006_alter_transaction_amount_bnb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=pag.models.generate_invoice_number, max_length=64, unique=True)),
                ('amount_ecg', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('amount_usdt', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('amount_bnb', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('is_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pag.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pag.userprofile')),
            ],
        ),
    ]
