# Generated by Django 5.2.8 on 2026-01-02 17:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0006_referral_staking_tokenreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staking',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenreward',
            name='reward_type',
            field=models.CharField(choices=[('signup_referral', 'پاداش ثبت نام زیرمجموعه'), ('staking_self', 'پاداش استیکینگ خود کاربر'), ('staking_referral', 'پاداش استیکینگ زیر مجموعه'), ('staking_unlock', 'برداشت از استیکینگ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('wallet_address', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_reward_at', models.DateTimeField(blank=True, null=True)),
                ('rewards_count', models.IntegerField(default=0)),
                ('referral_points', models.IntegerField(default=0)),
                ('balance_ecg', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_staked', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('total_rewards', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('flat_bonus_self', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('flat_bonus_upline', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='pag.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=200, unique=True)),
                ('transaction_type', models.CharField(choices=[('STAKE', 'Stake'), ('REWARD', 'Reward'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('amount_ecg', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('amount_usdt', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('amount_bnb', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('recipient_address', models.CharField(max_length=200)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pag.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='pag.userprofile')),
            ],
        ),
    ]
