# Generated by Django 5.2.8 on 2025-11-12 09:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0007_purchaseinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flat_bonus_self',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flat_bonus_upline',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36),
        ),
    ]
