# Generated by Django 5.2.8 on 2025-11-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag', '0008_userprofile_flat_bonus_self_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='transaction',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='last_monthly_reward_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='network',
            field=models.CharField(blank=True, default='bep20', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('destination_address', models.CharField(max_length=120)),
                ('network', models.CharField(default='bep20', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='pag.userprofile')),
            ],
        ),
    ]
